name: Kontact CI

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.3"

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec

